version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: assignment_mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE= assignment_mongo
    volumes:
      - mongo_data:/data/db 
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - ./backend:/app
    ports:
      - "8000:5000"
    command: ["python","app.py"]
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  mongo_data: